# test
kind: pipeline
type: docker
name: mullvad
platform:
  os: linux
  arch: arm64

steps:
  - name: mullvad-build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: n1ghtm4r3x/mullvad-docker
      dockerfile: Dockerfile
            
      tags:
        - latest
    when:
      event: 
        - push
        - pull_request
