kind: pipeline
name: mullvad

steps:
- name: clone
  image: plugins/git
  settings:
    depth: 1

- name: docker
  image: 
  environment:
    registry:
      from_secret: docker_registry
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo:
      from_secret: docker_repo
    tags: latest
