#kind: pipeline
#type: docker
#name: mullvad

#steps:
#- name: docker
#  image: plugins/docker
#  environment:
#    registry:
#      from_secret: docker_registry
#    username:
#      from_secret: docker_username
#    password:
#      from_secret: docker_passwordl
#    repo:
#      from_secret: docker_repo
#    tags: latest #
pipeline:
  ###############
  # S e r v e r #    username:

  ###############
  publish-server-dryrun:
    image: plugins/docker
  #  image: woodpeckerci/plugin-docker-buildx
   # secrets: [ docker_username, docker_password ]
    group: docker
    settings:
    #username:
     # from_secret: docker_username
    #password:
    #  from_secret: docker_password
    registry: registry.jbootsma.com
    repo: registry.jbootsma.com/cybergame/mullvad
    dockerfile: Dockerfile
      #platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le
    tag: test
    when:
      event: push
