#kind: pipeline
#type: docker
#name: mullvad
#
#steps:
#- name: docker
#  image: plugins/docker
#  environment:
#    registry:
#      from_secret: docker_registry
#    username:
#      from_secret: docker_usernamel
#    password:
#      from_secret: docker_passwordl
#    repo:
#      from_secret: docker_repo
#    tags: latest #
pipeline:
  ###############
  # S e r v e r #    username:

  ###############
  publish-server-dryrun:
    image: plugins/docker
    group: docker
    settings:
    registry: registry.jbootsma.com
    repo: registry.jbootsma.com/cybergame/mullvad
    dockerfile: Dockerfile
    platform: arm64
    tag: test
    when:
      event: push
