kind: pipeline
type: docker
name: mullvad

clone:

- name: docker
  image: plugins/docker
  environment:
    registry:
      from_secret: docker_registry
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo:
      from_secret: docker_repo
    tags: latest
