kind: pipeline
type: docker
name: mullvad

clone:
  depth: 1

steps:
- name: docker
  image: plugins/docker
  environment:
    registry:
      from_secret: docker_registry
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo:
      from_secret: docker_repo
    tags: latest

trigger:
  branch:
  - master
  event:
  - push
