kind: pipeline
name: mullvad
platform:
  os: linux
  arch: arm

steps:
  - name: mullvad-build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    registry: registry.jbootsma.com
    repo: registry.jbootsma.com/cybergame/mullvad
    dockerfile: Dockerfile
    tag: test
    when:
      event: push
