kind: pipeline
type: docker
name: mullvad
platform:
  os: linux
  arch: arm64

steps:
  - name: mullvad-build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry.jbootsma.com
      repo: registry.jbootsma.com/cybergame/mullvad
      dockerfile: Dockerfile
      tags:
        - test
    when:
      event: push
