#kind: pipelinel
#type: docker
#name: mullvad

#steps:
#- name: docker
#  image: plugins/docker
#  environment:
#    registry:
#      from_secret: docker_registry
#    username:
#      from_secret: docker_username
#    password:
#      from_secret: docker_password
#    repo:
#      from_secret: docker_repo
#    tags: latest
pipeline:
  ###############
  # S e r v e r #
  ###############
  publish-server-dryrun:
    image: plugins/docker
    group: docker
    settings:
      dry_run: false
      repo: registry.jbootsma.com/custom/mullvad
      dockerfile: Dockerfile
      #platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le
      tag: test
    when:
      event: push
