kind: pipeline
type: docker
name: mullvad
 publish-server-dryrun:
    image: plugins/docker
    group: docker
    settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: registry.jbootsma.com
    repo: registry.jbootsma.com/cybergame/mullvad
    dockerfile: Dockerfile
 #  platform: arm64
    tag: test
    when:
      event: push
