kind: pipeline
type: docker
name: mullvad
platform:
  os: linux
  arch: arm64

steps:
  - name: mullvad-build
    image: plugins/docker
    settings:
    registry: registry.jbootsma.com
    repo: registry.jbootsma.com/cybergame/mullvad
      USERNAME:
        from_secret: docker_username
      USERNAME:
        from_secret: docker_password
    dockerfile: Dockerfile
    tag: test
    when:
      event: push
