services:
  vpn:
    image: n1ghtm4r3x/mullvad-docker
    container_name: local-vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=Europe/Stockholm # Set timezone
      - ACCOUNT= # Add your mullvad account number without spaces
      - COUNTRY= # Choose the country you would like to use, Default is se (Sweden)      - LOCAL_SUBNET=192.168.1.0/24 # Add your local subnet
    volumes:
      - ./wg:/etc/wireguard # Set this to where you would like to save the wireguard config files
      - /lib/modules:/lib/modules:ro
    ports:
      - 8080:8080 # Example for linuxserver qbittorrent
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - WEBUI_PORT=8080
    volumes:
      - ./qbit/config:/config
      - ./qbit/downloads:/downloads
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
